# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    #branches: [ main ]
    tags:
         - 'test-*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    strategy:
      matrix:
        os:
          - runs-on: ubuntu-20.04
          - runs-on: ubuntu-18.04
    runs-on: ${{ matrix.os.runs-on }}
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Build packages
        run: |
            echo sudo apt install devscripts
            echo sudo apt install equivs
            echo  "VARS:" ${{ matrix.os.runs-on }}  $GITHUB_WORKFLOW
            mkdir ${{ matrix.os.runs-on }}
            cp package.1 package.2 ${{ matrix.os.runs-on }}
            #touch package.1
            #touch package.2
            #sudo mk-build-deps --install
            #make deb
      # https://github.com/marketplace/actions/upload-files-to-a-github-release
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_glob: true
          file: ${{ matrix.os.runs-on }}/package.*
          asset_name: package
          tag: ${{ github.ref }}
          overwrite: true
          body: "This is my release/tag text"
